const allBeads = () => {
	return [
		//Arabian
		{ number: '0027', patterns: 'Arabian' },
		{ number: '0051', patterns: 'Arabian' },
		{ number: '0117', patterns: 'Arabian' },
		{ number: '0250', patterns: 'Arabian' },
		{ number: '0501', patterns: 'Arabian' },
		{ number: '0624', patterns: 'Arabian' },
		{ number: '0871', patterns: 'Arabian' },
		{ number: '0284', patterns: 'Arabian' },
		{ number: '1805', patterns: 'Arabian' },

		//Consololation
		{ number: '0031', patterns: 'Consolation 2015' },
		{ number: '0112', patterns: 'Consolation 2015' },
		{ number: '0274', patterns: 'Consolation 2015' },
		{ number: '0629', patterns: 'Consolation 2015' },
		{ number: '0060', patterns: 'Consolation 2015' },
		{ number: '0276', patterns: 'Consolation 2015' },
		{ number: '0277', patterns: 'Consolation 2015' },

		//Dragonfly Tile
		{ number: '0010', patterns: 'Dragonfly Tile' },
		{ number: '0027', patterns: 'Dragonfly Tile' },
		{ number: '0052', patterns: 'Dragonfly Tile' },
		{ number: '0057', patterns: 'Dragonfly Tile' },
		{ number: '0084', patterns: 'Dragonfly Tile' },
		{ number: '0166', patterns: 'Dragonfly Tile' },
		{ number: '0285', patterns: 'Dragonfly Tile' },
		{ number: '0459', patterns: 'Dragonfly Tile' },
		{ number: '0501', patterns: 'Dragonfly Tile' },
		{ number: '0747', patterns: 'Dragonfly Tile' },
		{ number: '0862', patterns: 'Dragonfly Tile' },

		//Fairy Flora
		{ number: '0114', patterns: 'Fairy Flora' },
		{ number: '0027', patterns: 'Fairy Flora' },
		{ number: '1343', patterns: 'Fairy Flora' },
		{ number: '0117', patterns: 'Fairy Flora' },
		{ number: '0411', patterns: 'Fairy Flora' },
		{ number: '0051', patterns: 'Fairy Flora' },
		{ number: '0078', patterns: 'Fairy Flora' },
		{ number: '0058', patterns: 'Fairy Flora' },
		{ number: '0508', patterns: 'Fairy Flora' },
		{ number: '1455', patterns: 'Fairy Flora' },
		{ number: '0624', patterns: 'Fairy Flora' },

		//French Kitchen Garden
		{ number: '0057', patterns: 'French Kitchen Garden' },
		{ number: '0060', patterns: 'French Kitchen Garden' },
		{ number: '0501', patterns: 'French Kitchen Garden' },
		{ number: '0747', patterns: 'French Kitchen Garden' },
		{ number: '0779', patterns: 'French Kitchen Garden' },
		{ number: '0832', patterns: 'French Kitchen Garden' },
		{ number: '0922', patterns: 'French Kitchen Garden' },
		{ number: '1790', patterns: 'French Kitchen Garden' },
		{ number: '1812', patterns: 'French Kitchen Garden' },
		{ number: '1816', patterns: 'French Kitchen Garden' },

		//Hanging Gardens
		{ number: '0051', patterns: 'Hanging Gardens' },
		{ number: '0078', patterns: 'Hanging Gardens' },
		{ number: '0501', patterns: 'Hanging Gardens' },
		{ number: '0918', patterns: 'Hanging Gardens' },
		{ number: '1741', patterns: 'Hanging Gardens' },
		{ number: '1788', patterns: 'Hanging Gardens' },

		//Herbularus
		{ number: '0051', patterns: 'Herbularus' },
		{ number: '0864', patterns: 'Herbularus' },
		{ number: '0135', patterns: 'Herbularus' },
		{ number: '0125', patterns: 'Herbularus' },
		{ number: '0174', patterns: 'Herbularus' },
		{ number: '0858', patterns: 'Herbularus' },
		{ number: '0505', patterns: 'Herbularus' },
		{ number: '0296', patterns: 'Herbularus' },
		{ number: '0881', patterns: 'Herbularus' },
		{ number: '0078', patterns: 'Herbularus' },

		//Hummingbird Tile
		{ number: '0688', patterns: 'Hummingbird Tile' },
		{ number: '0047', patterns: 'Hummingbird Tile' },
		{ number: '0705', patterns: 'Hummingbird Tile' },
		{ number: '0501', patterns: 'Hummingbird Tile' },
		{ number: '0670', patterns: 'Hummingbird Tile' },
		{ number: '0413', patterns: 'Hummingbird Tile' },
		{ number: '0458', patterns: 'Hummingbird Tile' },
		{ number: '0879', patterns: 'Hummingbird Tile' },
		{ number: '0864', patterns: 'Hummingbird Tile' },
		{ number: '0274', patterns: 'Hummingbird Tile' },
		{ number: '0985', patterns: 'Hummingbird Tile' },
		{ number: '0917', patterns: 'Hummingbird Tile' },
		{ number: '0459', patterns: 'Hummingbird Tile' },

		//Hydrangea
		{ number: '0356', patterns: 'Autumn Hydrangea' },
		{ number: '0372', patterns: 'Autumn Hydrangea' },
		{ number: '0505', patterns: 'Autumn Hydrangea' },
		{ number: '0656', patterns: 'Autumn Hydrangea' },
		{ number: '0832', patterns: 'Autumn Hydrangea' },
		{ number: '1455', patterns: 'Autumn Hydrangea' },
		{ number: '1812', patterns: 'Autumn Hydrangea' },
		{ number: '1816', patterns: 'Autumn Hydrangea' },

		//Little Tuscany
		{ number: '0079', patterns: 'Little Tuscany' },
		{ number: '0859', patterns: 'Little Tuscany' },
		{ number: '1763', patterns: 'Little Tuscany' },
		{ number: '1783', patterns: 'Little Tuscany' },
		{ number: '1833', patterns: 'Little Tuscany' },

		//Mini Mandelas
		{ number: '0027', patterns: 'Mini Mandelas' },
		{ number: '0078', patterns: 'Mini Mandelas' },
		{ number: '0111', patterns: 'Mini Mandelas' },
		{ number: '0173', patterns: 'Mini Mandelas' },
		{ number: '0501', patterns: 'Mini Mandelas' },
		{ number: '0622', patterns: 'Mini Mandelas' },

		//Moss Garden
		{ number: '0053', patterns: 'Moss Garden' },
		{ number: '0331', patterns: 'Moss Garden' },
		{ number: '0458', patterns: 'Moss Garden' },
		{ number: '0906', patterns: 'Moss Garden' },
		{ number: '1109', patterns: 'Moss Garden' },
		{ number: '1845', patterns: 'Moss Garden' },
		{ number: '0165', patterns: 'Moss Garden' },
		{ number: '0373', patterns: 'Moss Garden' },
		{ number: '0624', patterns: 'Moss Garden' },

		//Peacock Tile
		{ number: '0027', patterns: 'Peacock Tile' },
		{ number: '0124', patterns: 'Peacock Tile' },
		{ number: '0458', patterns: 'Peacock Tile' },
		{ number: '0508', patterns: 'Peacock Tile' },
		{ number: '0607', patterns: 'Peacock Tile' },
		{ number: '0609', patterns: 'Peacock Tile' },
		{ number: '0610', patterns: 'Peacock Tile' },
		{ number: '1005', patterns: 'Peacock Tile' },
		{ number: '1006', patterns: 'Peacock Tile' },

		//Persian Iris
		{ number: '0047', patterns: 'Persian Iris' },
		{ number: '0051', patterns: 'Persian Iris' },
		{ number: '0057', patterns: 'Persian Iris' },
		{ number: '0230', patterns: 'Persian Iris' },
		{ number: '0331', patterns: 'Persian Iris' },
		{ number: '0374', patterns: 'Persian Iris' },
		{ number: '0608', patterns: 'Persian Iris' },
		{ number: '0694', patterns: 'Persian Iris' },
		{
			number: '0480',
			patterns: 'Persian Iris',
			message: 'Bead is discontinued'
		},
		{ number: '0230', patterns: 'Persian Iris flower' },
		{ number: '0080', patterns: 'Persian Iris flower' },
		{ number: '0125', patterns: 'Persian Iris flower' },
		{ number: '0117', patterns: 'Persian Iris flower' },
		{ number: '0906', patterns: 'Persian Iris flower' },
		{ number: '0124', patterns: 'Persian Iris flower' },
		{ number: '0079', patterns: 'Persian Iris flower' },

		//Rainforest
		{ number: '0010', patterns: 'Rainforest' },
		{ number: '0047', patterns: 'Rainforest' },
		{ number: '0057', patterns: 'Rainforest' },
		{ number: '0112', patterns: 'Rainforest' },
		{ number: '0125', patterns: 'Rainforest' },
		{ number: '0275', patterns: 'Rainforest' },
		{ number: '0410', patterns: 'Rainforest' },
		{ number: '0670', patterns: 'Rainforest' },
		{ number: '0693', patterns: 'Rainforest' },
		{ number: '0747', patterns: 'Rainforest' },
		{ number: '0755', patterns: 'Rainforest' },
		{ number: '0795', patterns: 'Rainforest' },
		{ number: '1249', patterns: 'Rainforest' },
		{ number: '1505', patterns: 'Rainforest' },
		{ number: '1578', patterns: 'Rainforest' },
		{ number: '1731', patterns: 'Rainforest' },
		{ number: '0077', patterns: 'Rainforest' },
		{ number: '0276', patterns: 'Rainforest' },
		{ number: '0029', patterns: 'Rainforest' },
		{ number: '0297', patterns: 'Rainforest' },
		{ number: '0777', patterns: 'Rainforest' },
		{ number: '0856', patterns: 'Rainforest' },
		{ number: '1585', patterns: 'Rainforest' },

		//Seville
		{ number: '0034', patterns: 'Seville' },
		{ number: '0035', patterns: 'Seville' },
		{ number: '0058', patterns: 'Seville' },
		{ number: '0177', patterns: 'Seville' },
		{ number: '1710', patterns: 'Seville' },
		{ number: '1741', patterns: 'Seville' },
		{ number: '1766', patterns: 'Seville' },
		{ number: '1812', patterns: 'Seville' },
		{ number: '1764', patterns: 'Seville' },

		//Sparkling Peacock
		{ number: '0501', patterns: 'Sparkling Peacock' },
		{ number: '0918', patterns: 'Sparkling Peacock' },
		{ number: '0051', patterns: 'Sparkling Peacock' },
		{ number: '1769', patterns: 'Sparkling Peacock' },
		{ number: '0688', patterns: 'Sparkling Peacock' },
		{ number: '0152', patterns: 'Sparkling Peacock' },
		{ number: '0031', patterns: 'Sparkling Peacock' },
		{ number: '0276', patterns: 'Sparkling Peacock' },
		{ number: '0174', patterns: 'Sparkling Peacock' },

		//Tinctorium
		{ number: '0031', patterns: 'Tinctorium' },
		{ number: '0109', patterns: 'Tinctorium' },
		{ number: '0112', patterns: 'Tinctorium' },
		{ number: '0237', patterns: 'Tinctorium' },
		{ number: '0276', patterns: 'Tinctorium' },
		{ number: '0626', patterns: 'Tinctorium' },
		{ number: '0694', patterns: 'Tinctorium' },
		{ number: '0861', patterns: 'Tinctorium' },

		//Vineyard
		{ number: '0051', patterns: 'Vineyard' },
		{ number: '0170', patterns: 'Vineyard' },
		{ number: '0233', patterns: 'Vineyard' },
		{ number: '0238', patterns: 'Vineyard' },
		{ number: '0858', patterns: 'Vineyard' },
		{ number: '0880', patterns: 'Vineyard' },
		{ number: '0922', patterns: 'Vineyard' },
		{ number: '1005', patterns: 'Vineyard' },
		{ number: '1185', patterns: 'Vineyard' },
		{ number: '1247', patterns: 'Vineyard' },

		//Watergarden
		{ number: '0324', patterns: 'Watergarden' },
		{ number: '0352', patterns: 'Watergarden' },
		{ number: '0354', patterns: 'Watergarden' },
		{ number: '0355', patterns: 'Watergarden' },
		{ number: '0373', patterns: 'Watergarden' },
		{ number: '0415', patterns: 'Watergarden' },
		{ number: '0501', patterns: 'Watergarden' },
		{ number: '0622', patterns: 'Watergarden' },
		{ number: '0670', patterns: 'Watergarden' },
		{ number: '0877', patterns: 'Watergarden' },
		{ number: '0010', patterns: 'Watergarden' }
	];
}
export default allBeadsReducer;
