export const SEARCH_PATTERNS = 'SEARCH_PATTERNS';
export const SEARCH_BEADS = 'SEARCH_PATTERNS';
export const SEARCH_SILKS = 'SEARCH_PATTERNS';
export const SEARCH_DMC = 'SEARCH_PATTERNS';
export const SEARCH_METALLICS = 'SEARCH_PATTERNS';
export const CLEAR_SEARCH = CLEAR_SEARCH;
