export const metallics = [
  { type: 'PB', number: '01', patterns: ["Fairy Flora", "Hanging Gardens", "Little Tuscany", "Persian Iris", "Watergarden"], color: "Bright Gold" },
  { type: "PB", number: "02", patterns: ["Consolation", "Hydrangea"], color: "Arctic Gold" },
  { type: "PB", number: "04", patterns: ["Fairy Flora", "Moss Garden", "Tinctorium"], color: "Silver" },
  { type: "PB", number: "05", patterns: ["Arabian", "French Kitchen Garden", "Rainforest"], color: "Black" },
  { type: "PB", number: "06", patterns: ["Rainforest"], color: "Green" },
  { type: "PB", number: "08", patterns: ["Hanging Gardens"], color: "Blue" },
  { type: "PB", number: "09", patterns: ["Arabian", "Persian Iris"], color: "Sky Blue" },
  { type: "SP", number: "010", patterns: ["Persian Iris"] },
  { type: "PB", number: "14", patterns: ["Sparkling Peacock"], color: "Bronze" },
  { type: "PB", number: "17", patterns: ["Hanging Gardens", "Moss Garden"], color: "Water Blue" },

  { type: 'PB', number: '20', patterns: ["Consolation", "Peacock Tile"], color: 'Green' },
  { type: "PB", number: "21", patterns: ["Hydrangea"], color: "Copper" },
  { type: 'PB', number: '25', patterns: ["French Kitchen Garden", "Seville"], color: 'Old Gold' },
  { type: "PB", number: "26", patterns: ["Hanging Gardens", "Mini Mandelas", "Moss Garden", "Rainforest"], color: "Aztec Gold" },
  { type: "PB", number: "31", patterns: ["Rainforest"], color: "Evergreen" },
  { type: "PB", number: "32", patterns: ["Mini Mandelas"], color: "Pewter" },
  { type: "PB", number: "33", patterns: ["Sparkling Peacock", "Seville"], color: "Blue" },
  { type: "PB", number: "35", patterns: ["Arabian", "Dragonfly Tile", "Hummingbird Tile", "Peacock Tile", "Persian Iris", "Seville", "Sparkling Peacock"], color: "Dark Gold" },
  { type: "PB", number: "38", patterns: ["Sparkling Peacock"], color: "Azure" },
  { type: "PB", number: "36", patterns: ["Gothic Arch", "Hanging Gardens", "Rainforest"], color: "Antique Gold" },
  { type: "PB", number: "40", patterns: ["Persian Iris", "Rainforest"], color: "Egyptian Gold" },
  { type: "PB", number: "43", patterns: ["Peacock Tile", "Sparkling Peacock"], color: "Turquoise" },
  { type: "PB", number: "47", patterns: ["Arabian", "Seville"], color: "Ice" },
  { type: "PB", number: "50", patterns: ["Moss Garden"], color: "Seashell" },
  { type: "PB", number: "51", patterns: ["Moss Garden"], color: "Dark Chocolate" },

  { type: "PB", number: "52", patterns: "Sparkling Peacock", color: "Lighter Green" },
  { type: "PB", number: "54", patterns: ["Gothic Arch"], color: "Vatican Gold" },
  { type: "PB", number: "56", patterns: ["Rainforest"], color: "Pale Avocado" },
  { type: "PB", number: "57", patterns: "Seville", color: "Avocado" },
  { type: "PB", number: "58", patterns: ["Hydrangea"], color: "Antique Silver" },
  { type: "PB", number: "59", patterns: ["Gothic Arch", "Tinctorium"], color: "Black Silver" },
  { type: "PB", number: "63", patterns: ["Vineyard"], color: "Deep Midnight Blue" },
  { type: "PB", number: "204", patterns: ["Moss Garden", "Seville", "Tinctorium"], color: "Blue Pearl" },


  { type: "SP", number: "013", patterns: ["Vineyard"] },
  { type: "SP", number: "018", patterns: ["Dragonfly Tile", "Hummingbird Tile", "Gothic Arch", "Moss Garden", "Peacock Tile"] },
  { type: "SP", number: "019", patterns: ["Sparkling Peacock"] },
  { type: "SP", number: "021", patterns: ["Sparkling Peacock"] },
  { type: "SP", number: "032", patterns: ["Vineyard"] },
  { type: "SP", number: "035", patterns: ["Moss Garden", "Vineyard"] },
  { type: 'SP', number: '036', patterns: ["Seville"] },
  { type: "SP", number: "038", patterns: ["Little Tuscany", "Rainforest", "Sparkling Peacock"] },
  { type: 'SP', number: '039', patterns: ["Seville", "Sparkling Peacock"] },
  { type: "SP", number: "058", patterns: ["Seville"] },
  { type: "SP", number: "047", patterns: ["Fairy Flora"], color: "Fosty Sparkle" },
  { type: "SP", number: "051", patterns: ["French Kitchen Garden"] },
  { type: "SP", number: "060", patterns: ["Tinctorium"] },
  { type: "SP", number: "061", patterns: ["Vineyard"] },
  { type: "SP", number: "062", patterns: ["Seville"] },
  { type: "SP", number: "064", patterns: ["Sparkling Peacock", "Vineyard"] },
  { type: "SP", number: "068", patterns: ["French Kitchen Garden", "Sparkling Peacock"] },
  { type: "SP", number: "069", patterns: ["Tinctorium"] },
  { type: "SP", number: "077", patterns: ["Seville"] },
  { type: "SP", number: "119", patterns: ["Gothic Arch"], color: "Blue Sapphire" },
  { type: "SP", number: "139", patterns: ["Gothic Arch"] },
  { type: "SP", number: "183", patterns: ["Gothic Arch"] },
  { type: 'SP', number: "113", patterns: ["Moss Garden", "Gothic Arch", "Peacock Tile", "Sparkling Peacock", "Vineyard"] },
  { type: "SP", number: "118", patterns: "Sparkling Peacock", color: "Sea Spray" }



];
